### ISSUE TITLE
README File Missing License Information and Not Following Standard Protocol

### ISSUE THREAD

**Issue by CodingSamm** [Sudhaanshuu/Portfolio-Sudhanshu#1]
## Issue Description
The README file currently lacks a mention of the project license and does not adhere to standard protocol for documentation.

## Steps to Reproduce
- Open the README file in the project repository.
- Observe the absence of license information.
- Review the overall structure and content to note deviations from standard documentation practices.

## Expected Behavior:

- The README file should include a clear section specifying the project's license to inform users of their rights and obligations.
- The README should follow standard documentation protocols to ensure clarity and consistency.

**Comment by Sudhaanshuu** [comment]
Hi Vashudeev,

Thank you for bringing this to our attention. Your detailed issue report regarding the missing license information and the need for adherence to standard documentation protocols is greatly appreciated.

I agree with your proposed solution to add a license section and reorganize the README file for better clarity and consistency. This enhancement will significantly improve our project's documentation.
